# Generated by Django 4.1.3 on 2024-02-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripexpensetrackerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
